export const ADMIN_PERMISSIONS = {
  ADMIN_VIEW: "ADMIN_VIEW",
  ADMIN_CREATE: "ADMIN_CREATE",
  ADMIN_STATUS_MANAGE: "ADMIN_STATUS_MANAGE",
  ADMIN_DEACTIVATE: "ADMIN_DEACTIVATE",

  REPORT_MANAGE: "REPORT_MANAGE",
  USER_SUSPEND: "USER_SUSPEND",
  INQUIRY_MANAGE: "INQUIRY_MANAGE",
  NOTICE_MANAGE: "NOTICE_MANAGE",
  FAQ_MANAGE: "FAQ_MANAGE",
  TERMS_MANAGE: "TERMS_MANAGE",
  REVIEW_MANAGE: "REVIEW_MANAGE",
  RESIDENCE_REVIEW_MANAGE: "RESIDENCE_REVIEW_MANAGE",
  GIVEAWAY_MANAGE: "GIVEAWAY_MANAGE",
  ESTIMATE_MANAGE: "ESTIMATE_MANAGE",
} as const;

export type AdminPermission = (typeof ADMIN_PERMISSIONS)[keyof typeof ADMIN_PERMISSIONS];
