import type { AdminRole } from "@prisma/client";

import { ADMIN_PERMISSIONS, type AdminPermission } from "./admin-permissions";

export const ADMIN_ROLE_PERMISSIONS: Record<AdminRole, readonly AdminPermission[]> = {
  SUPER_ADMIN: [
    ADMIN_PERMISSIONS.ADMIN_VIEW,
    ADMIN_PERMISSIONS.ADMIN_CREATE,
    ADMIN_PERMISSIONS.ADMIN_STATUS_MANAGE,
    ADMIN_PERMISSIONS.ADMIN_DEACTIVATE,
  ],

  ADMIN: [
    ADMIN_PERMISSIONS.REPORT_MANAGE,
    ADMIN_PERMISSIONS.USER_SUSPEND,
    ADMIN_PERMISSIONS.INQUIRY_MANAGE,
    ADMIN_PERMISSIONS.NOTICE_MANAGE,
    ADMIN_PERMISSIONS.FAQ_MANAGE,
    ADMIN_PERMISSIONS.TERMS_MANAGE,
  ],
};
