export const MOVERS = [
  {
    email: "mover1@test.com",
    name: "김민수",
    phone: "010-2000-0001",
    nickname: "빠른이사",
    career: 3,
    shortIntro: "빠르고 안전한 이사를 도와드립니다.",
    description:
      "소형 이사와 가정 이사를 전문으로 합니다. 고객님의 소중한 물건을 안전하고 신속하게 운반하겠습니다.",
    confirmedCount: 18,
    averageRating: 0,
    reviewCount: 0,
    regions: ["서울", "경기", "인천"],
    moveTypes: ["SMALL", "HOME"],
    businessNumber: "101-45-67891",
    businessName: "테스트이사1",
    approvalStatus: "APPROVED",
  },
  {
    email: "mover2@test.com",
    name: "이서준",
    phone: "010-2000-0002",
    nickname: "든든이사",
    career: 7,
    shortIntro: "든든하고 꼼꼼한 이사 서비스를 제공합니다.",
    description: "다년간의 경험을 바탕으로 포장부터 운반까지 꼼꼼하게 진행합니다.",
    confirmedCount: 42,
    averageRating: 0,
    reviewCount: 0,
    regions: ["서울", "경기"],
    moveTypes: ["HOME", "OFFICE"],
    businessNumber: "102-45-67892",
    businessName: "테스트이사2",
    approvalStatus: "APPROVED",
  },
  {
    email: "mover3@test.com",
    name: "박지훈",
    phone: "010-2000-0003",
    nickname: "행복이사",
    career: 12,
    shortIntro: "새로운 시작을 행복하게 만들어드립니다.",
    description: "풍부한 현장 경험을 바탕으로 고객 상황에 맞는 이사 서비스를 제공합니다.",
    confirmedCount: 86,
    averageRating: 0,
    reviewCount: 0,
    regions: ["부산", "울산", "경남"],
    moveTypes: ["SMALL", "HOME", "OFFICE"],
    businessNumber: "103-45-67893",
    businessName: "테스트이사3",
    approvalStatus: "APPROVED",
  },
  {
    email: "mover4@test.com",
    name: "최도윤",
    phone: "010-2000-0004",
    nickname: "친절이사",
    career: 5,
    shortIntro: "친절한 상담과 정직한 견적을 약속드립니다.",
    description: "고객과 충분히 소통하고 필요한 서비스만 정직하게 안내합니다.",
    confirmedCount: 29,
    averageRating: 0,
    reviewCount: 0,
    regions: ["대전", "세종", "충남", "충북"],
    moveTypes: ["SMALL", "HOME"],
    businessNumber: "104-45-67894",
    businessName: "테스트이사4",
    approvalStatus: "APPROVED",
  },
  {
    email: "mover5@test.com",
    name: "정현우",
    phone: "010-2000-0005",
    nickname: "베테랑이사",
    career: 18,
    shortIntro: "18년 경력의 베테랑 기사입니다.",
    description: "가정 이사부터 대규모 사무실 이사까지 다양한 경험을 보유하고 있습니다.",
    confirmedCount: 154,
    averageRating: 0,
    reviewCount: 0,
    regions: ["대구", "경북", "경남"],
    moveTypes: ["HOME", "OFFICE"],
    businessNumber: "105-45-67895",
    businessName: "테스트이사5",
    approvalStatus: "APPROVED",
  },
  {
    email: "mover6@test.com",
    name: "강우진",
    phone: "010-2000-0006",
    nickname: "안심이사",
    career: 9,
    shortIntro: "고객이 안심할 수 있는 이사를 진행합니다.",
    description: "포장과 운반 과정에서 파손이 발생하지 않도록 꼼꼼하게 작업합니다.",
    confirmedCount: 63,
    averageRating: 0,
    reviewCount: 0,
    regions: ["광주", "전남", "전북"],
    moveTypes: ["SMALL", "HOME", "OFFICE"],
    businessNumber: "106-45-67896",
    businessName: "테스트이사6",
    approvalStatus: "APPROVED",
  },
  {
    email: "mover7@test.com",
    name: "조성민",
    phone: "010-2000-0007",
    nickname: "깔끔이사",
    career: 4,
    shortIntro: "처음부터 마무리까지 깔끔하게 진행합니다.",
    description: "원룸과 소형 이사를 중심으로 신속하고 깔끔한 서비스를 제공합니다.",
    confirmedCount: 24,
    averageRating: 0,
    reviewCount: 0,
    regions: ["강원", "경기", "서울"],
    moveTypes: ["SMALL", "HOME"],
    businessNumber: "107-45-67897",
    businessName: "테스트이사7",
    approvalStatus: "REJECTED",
    rejectReason: "사업자등록증 이미지가 흐릿하여 확인이 어렵습니다. 재제출 부탁드립니다.",
  },
  {
    email: "mover8@test.com",
    name: "윤재현",
    phone: "010-2000-0008",
    nickname: "제주이사",
    career: 10,
    shortIntro: "제주 지역 전문 이사 기사입니다.",
    description: "제주 지역의 이동 환경을 이해하고 안전한 이사 서비스를 제공합니다.",
    confirmedCount: 71,
    averageRating: 0,
    reviewCount: 0,
    regions: ["제주"],
    moveTypes: ["SMALL", "HOME"],
    businessNumber: "108-45-67898",
    businessName: "테스트이사8",
    approvalStatus: "PENDING",
  },
] as const;
